### ISSUE TITLE
The output pane always shows `fork/exec : no such file or directory`

### ISSUE THREAD

**Issue by neilco** [nkoporec/ginker#1]
### Summary: 

The output pane always shows `fork/exec : no such file or directory`. 

### Steps to Reproduce:

- Download the [v0.1.0 DMG](https://github.com/nkoporec/ginker/releases/tag/v0.1.0)
- Install **Ginker** into **`/Applications`**
- Run **Ginker**
- Set the **Golang Binary** path to `/usr/local/go/bin/go` in preferences (because it was empty)
- Modify the **string argument** to `fmt.Println`. 

### Environment:

- macOS 11.3.1 (Big Sur)
- Go 1.16.4 (installed from official package)

### Expected Outcome:

- The output pane shows the modified string

### Actual Outcome:

- The output pane shows `fork/exec : no such file or directory`. 

<img width="1136" alt="Nope" src="https://user-images.githubusercontent.com/59509/118970209-e208e000-b965-11eb-9887-0b0feedfae74.png">

**Comment by nkoporec** [comment]
I suspect that the 'Golang binary' path does not work correctly on Mac OS, since it was empty as first. I'm using it on my workstation(linux) and the go path does get populated at startup.I will try to replicate the issue on my mac later in the day.

**Comment by neilco** [comment]
[This line](https://github.com/nkoporec/ginker/blob/2579c4cfbb3166a1cfea7a05436bdac1b464f749/compiler/config.go#L65) shows that the `"darwin"` case is empty and this explains why the Golang Binary path is empty under macOS. It will not fall through to the `"linux"` case, which is what I suspect you intend. The right way is shown below:

```go
switch os := runtime.GOOS; os {
case "darwin":
  fallthrough
case "linux":
  cmd := exec.Command("which", "go")
  stdout, err := cmd.Output()

  if err != nil {
  }
  goBinary = string(stdout)
}
```

An alternative approach is shown here: 

```go
switch os := runtime.GOOS; os {
case "darwin", "linux":
  cmd := exec.Command("which", "go")
  stdout, err := cmd.Output()

  if err != nil {
  }
  goBinary = string(stdout)
}
```

**Comment by nkoporec** [comment]
Yep you were right, the switch case was ignored. I published a new release where this is fixed + the gobinary path should also work now.

Let me know, if it works.

**Comment by neilco** [comment]
I removed  my Ginker config (`rm -rf ~/.ginker`) and ran v0.1.1. The issue remained, so I did some digging... 

**Fun fact:** Forking a child process from within macOS app bundle **_does not inherit the environment_** of the user that launched the app bundle 🤦 

I got it working by appending `$GOROOT/bin` to `$PATH`:

```go
switch runtime.GOOS {
case "darwin", "linux":
  // Configure $PATH with a sensible default
  defaultGoBin := filepath.Clean(path.Join(runtime.GOROOT(), "bin"))
  os.Setenv("PATH", fmt.Sprintf("%s:%s", os.Getenv("PATH"), defaultGoBin))
  
  cmd := exec.Command("which", "go")
  stdout, err := cmd.Output()

  if err != nil {
  }
  goBinary = string(stdout)
}
```

A safer approach would be this:

```go
switch runtime.GOOS {
case "darwin", "linux":  
  cmd := exec.Command("which", "go")
  stdout, err := cmd.Output()

  if err != nil {
  }
  goBinary = string(stdout)
  if goBinary == "" && runtime.GOROOT() != "" {
    goBinary = filepath.Clean(path.Join(runtime.GOROOT(), "bin", "go"))
  }
}
```

**Comment by nkoporec** [comment]
Nice, did not think of running the app inside the app bundle. I committed your suggestions to the master branch :+1:
